# Generated by Django 3.2.9 on 2021-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211115_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
