# Generated by Django 3.2.9 on 2021-11-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/avatar.svg', null=True, upload_to='profiles/'),
        ),
    ]
