# Generated by Django 3.2.9 on 2021-11-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
