# Generated by Django 3.2.9 on 2021-11-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.BinaryField(blank=True, max_length=256, null=True),
        ),
    ]
